# Application Configuration
server:
  port: 8091

# Spring
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product-service?useUnicode=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

#spring:
#  application:
#    name: product-service
#  cloud:
#    config:
#      uri: http://localhost:8081
#      username: root
#      password: s3cr3t

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"